
namespace UtfUnknown.Core.Models.SingleByte.German
{
    public class Ibm850_GermanModel : GermanModel
    {
        // Generated by BuildLangModel.py
        // On: 2016-09-21 03:28:11.733089

        // Character Mapping Table:
        // ILL: illegal character.
        // CTR: control character specific to the charset.
        // RET: carriage/return.
        // SYM: symbol (punctuation) that does not belong to word.
        // NUM: 0 - 9.

        // Other characters are ordered by probabilities
        // (0 is the most common character in the language).

        // Orders are generic to a language. So the codepoint with order X in
        // CHARSET1 maps to the same character as the codepoint with the same
        // order X in CHARSET2 for the same language.
        // As such, it is possible to get missing order. For instance the
        // ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
        // even though they are both used for French. Same for the euro sign.

        private static byte[] CHAR_TO_ORDER_MAP = {
            CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
            CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
            SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
            NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
            SYM,  5, 15, 12,  8,  0, 17, 14,  7,  3, 23, 16,  9, 13,  2, 11, /* 4X */
             18, 30,  1,  4,  6, 10, 21, 19, 28, 25, 20,SYM,SYM,SYM,SYM,SYM, /* 5X */
            SYM,  5, 15, 12,  8,  0, 17, 14,  7,  3, 23, 16,  9, 13,  2, 11, /* 6X */
             18, 30,  1,  4,  6, 10, 21, 19, 28, 25, 20,SYM,SYM,SYM,SYM,CTR, /* 7X */
             35, 24, 29, 37, 22, 41, 49, 35, 48, 43, 32, 52, 47, 57, 44, 49, /* 8X */
             32, 50, 50, 40, 26, 51, 63, 58, 56, 26, 24, 38,SYM, 38,SYM, 59, /* 9X */
             31, 33, 34, 46, 39, 39,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
            SYM,SYM,SYM,SYM,SYM, 31, 37, 41,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
            SYM,SYM,SYM,SYM,SYM,SYM, 44, 44,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* CX */
             53, 53, 48, 43, 32,SYM, 33, 47, 52,SYM,SYM,SYM,SYM,SYM, 57,SYM, /* DX */
             34, 27, 40, 51, 55, 55, 60, 62, 64, 46, 61, 58, 45, 45,SYM,SYM, /* EX */
            SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* FX */
        };
        /*   X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

        public Ibm850_GermanModel() : base(CHAR_TO_ORDER_MAP, CodepageName.IBM850)
        {
        }
    }
}
